# Generated by Django 2.2.16 on 2020-09-29 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateTimeField(help_text='Date start Meetup')),
                ('description', models.TextField(blank=True)),
                ('count_beer', models.IntegerField(default=0, help_text='Count Beer')),
                ('maximum_temperature', models.FloatField(blank=True, default=0, help_text='Maximum Temperature')),
                ('count_participants', models.IntegerField(default=0, help_text='Count Participants')),
                ('direction', models.CharField(max_length=350)),
            ],
            options={
                'verbose_name_plural': 'Meetup',
            },
        ),
    ]
