# Generated by Django 2.2.16 on 2020-09-30 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_meetup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='direction',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='MeetupEnrollInviteUsers',
            fields=[
                ('id', models.AutoField(help_text='Unique id', primary_key=True, serialize=False)),
                ('user_check_in', models.BooleanField(default=False)),
                ('meetup', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Meetup_MeetupEnrollInviteUsers', to='core.Meetup')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='User_MeetupEnrollInviteUsers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Meetup Enroll InviteUsers',
            },
        ),
    ]
