# Generated by Django 2.2.16 on 2020-09-30 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200930_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='count_box_beer',
            field=models.IntegerField(default=0, help_text='Count Box beer'),
        ),
        migrations.AlterField(
            model_name='meetup',
            name='count_beer',
            field=models.IntegerField(default=0, help_text='quantity of beer expressed in boxes of 6 units'),
        ),
        migrations.AlterField(
            model_name='meetup',
            name='direction',
            field=models.CharField(max_length=380),
        ),
    ]
