# Generated by Django 3.1.2 on 2020-10-02 03:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201002_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User_Meetup', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='meetupenrollinviteusers',
            unique_together={('user', 'meetup')},
        ),
    ]
